<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Categorie;
use App\Models\Question;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Nettoyage préalable
        Categorie::truncate();
        Question::truncate();

        $categories = [
            'Histoire',
            'Cinéma',
            'Sport',
            'Géographie',
            'Sciences'
        ];

        foreach ($categories as $cat) {
            Categorie::create(['categorie' => $cat]);
        }

        $questions = [
            // =========================================================
            // HISTOIRE (10 questions)
            // =========================================================
            [
                'categorie' => 'Histoire',
                'question' => 'En quelle année a eu lieu la prise de la Bastille ?',
                'reponse1' => '1789',
                'reponse2' => '1792',
                'reponse3' => '1776',
                'reponse4' => '1804',
                'reponse5' => '1785',
                'reponse6' => '1799',
                'reponse7' => '1750',
                'reponse8' => '1815',
                'reponse9' => '1768',
                'reponse10' => '1793',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'Qui était le premier empereur des Français ?',
                'reponse1' => 'Napoléon Ier',
                'reponse2' => 'Louis XIV',
                'reponse3' => 'Napoléon III',
                'reponse4' => 'Charlemagne',
                'reponse5' => 'François Ier',
                'reponse6' => 'Henri IV',
                'reponse7' => 'Louis XVI',
                'reponse8' => 'Clovis',
                'reponse9' => 'Charles de Gaulle',
                'reponse10' => 'Philippe le Bel',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'Quel traité a mis fin à la Première Guerre mondiale en 1919 ?',
                'reponse1' => 'Traité de Versailles',
                'reponse2' => 'Traité de Rome',
                'reponse3' => 'Traité de Maastricht',
                'reponse4' => 'Traité de Vienne',
                'reponse5' => 'Traité de Tordesillas',
                'reponse6' => 'Traité d\'Utrecht',
                'reponse7' => 'Traité de Paris',
                'reponse8' => 'Traité de Brest-Litovsk',
                'reponse9' => 'Traité de Gand',
                'reponse10' => 'Traité de Verdun',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'En quelle année l\'Homme a-t-il marché sur la Lune pour la première fois ?',
                'reponse1' => '1969',
                'reponse2' => '1965',
                'reponse3' => '1971',
                'reponse4' => '1959',
                'reponse5' => '1968',
                'reponse6' => '1972',
                'reponse7' => '1962',
                'reponse8' => '1975',
                'reponse9' => '1967',
                'reponse10' => '1970',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'Quelle reine d\'Égypte a séduit Jules César et Marc Antoine ?',
                'reponse1' => 'Cléopâtre VII',
                'reponse2' => 'Néfertiti',
                'reponse3' => 'Hatchepsout',
                'reponse4' => 'Néfertari',
                'reponse5' => 'Arsinoé',
                'reponse6' => 'Bérénice',
                'reponse7' => 'Tiyi',
                'reponse8' => 'Mérytaton',
                'reponse9' => 'Nitocris',
                'reponse10' => 'Twosret',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'En quelle année est tombé le mur de Berlin ?',
                'reponse1' => '1989',
                'reponse2' => '1991',
                'reponse3' => '1985',
                'reponse4' => '1975',
                'reponse5' => '1980',
                'reponse6' => '1993',
                'reponse7' => '1961',
                'reponse8' => '1988',
                'reponse9' => '1982',
                'reponse10' => '1990',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'À quelle date s\'est déroulé le Débarquement allié en Normandie ?',
                'reponse1' => '6 juin 1944',
                'reponse2' => '8 mai 1945',
                'reponse3' => '18 juin 1940',
                'reponse4' => '11 novembre 1943',
                'reponse5' => '14 juillet 1944',
                'reponse6' => '15 août 1944',
                'reponse7' => '6 juin 1943',
                'reponse8' => '1er septembre 1939',
                'reponse9' => '25 août 1944',
                'reponse10' => '6 mai 1945',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'Quel roi de France était surnommé le "Roi-Soleil" ?',
                'reponse1' => 'Louis XIV',
                'reponse2' => 'Louis XV',
                'reponse3' => 'Louis XVI',
                'reponse4' => 'François Ier',
                'reponse5' => 'Henri IV',
                'reponse6' => 'Saint Louis',
                'reponse7' => 'Charles IX',
                'reponse8' => 'Louis XIII',
                'reponse9' => 'Philippe Auguste',
                'reponse10' => 'Louis XI',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'En quelle année a eu lieu la Révolution russe menée par les Bolcheviks ?',
                'reponse1' => '1917',
                'reponse2' => '1905',
                'reponse3' => '1914',
                'reponse4' => '1922',
                'reponse5' => '1919',
                'reponse6' => '1924',
                'reponse7' => '1912',
                'reponse8' => '1936',
                'reponse9' => '1918',
                'reponse10' => '1920',
            ],
            [
                'categorie' => 'Histoire',
                'question' => 'En quelle année Christophe Colomb a-t-il atteint les Amériques ?',
                'reponse1' => '1492',
                'reponse2' => '1515',
                'reponse3' => '1453',
                'reponse4' => '1502',
                'reponse5' => '1488',
                'reponse6' => '1498',
                'reponse7' => '1520',
                'reponse8' => '1475',
                'reponse9' => '1534',
                'reponse10' => '1469',
            ],

            // =========================================================
            // CINÉMA (10 questions)
            // =========================================================
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel réalisateur a réalisé le film "Inception" ?',
                'reponse1' => 'Christopher Nolan',
                'reponse2' => 'Steven Spielberg',
                'reponse3' => 'James Cameron',
                'reponse4' => 'Quentin Tarantino',
                'reponse5' => 'David Fincher',
                'reponse6' => 'Martin Scorsese',
                'reponse7' => 'Ridley Scott',
                'reponse8' => 'Denis Villeneuve',
                'reponse9' => 'Stanley Kubrick',
                'reponse10' => 'Peter Jackson',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Combien d\'Oscars le film Titanic (1997) a-t-il remportés ?',
                'reponse1' => '11',
                'reponse2' => '9',
                'reponse3' => '12',
                'reponse4' => '10',
                'reponse5' => '8',
                'reponse6' => '14',
                'reponse7' => '7',
                'reponse8' => '13',
                'reponse9' => '6',
                'reponse10' => '5',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel acteur incarne Tony Stark / Iron Man dans le Marvel Cinematic Universe ?',
                'reponse1' => 'Robert Downey Jr.',
                'reponse2' => 'Chris Evans',
                'reponse3' => 'Chris Hemsworth',
                'reponse4' => 'Mark Ruffalo',
                'reponse5' => 'Tom Cruise',
                'reponse6' => 'Benedict Cumberbatch',
                'reponse7' => 'Christian Bale',
                'reponse8' => 'Johnny Depp',
                'reponse9' => 'Brad Pitt',
                'reponse10' => 'Keanu Reeves',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Dans quel film culte entend-on la réplique "Que la Force soit avec toi" ?',
                'reponse1' => 'Star Wars',
                'reponse2' => 'Star Trek',
                'reponse3' => 'Matrix',
                'reponse4' => 'Le Seigneur des Anneaux',
                'reponse5' => 'Blade Runner',
                'reponse6' => 'Dune',
                'reponse7' => 'Avatar',
                'reponse8' => 'Interstellar',
                'reponse9' => 'Harry Potter',
                'reponse10' => 'E.T.',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Qui a composé la célèbre bande originale du film "Le Fabuleux Destin d\'Amélie Poulain" ?',
                'reponse1' => 'Yann Tiersen',
                'reponse2' => 'Hans Zimmer',
                'reponse3' => 'Ennio Morricone',
                'reponse4' => 'Alexandre Desplat',
                'reponse5' => 'John Williams',
                'reponse6' => 'Ludovico Einaudi',
                'reponse7' => 'Max Richter',
                'reponse8' => 'Danny Elfman',
                'reponse9' => 'Howard Shore',
                'reponse10' => 'Gabriel Yared',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel réalisateur a réalisé "Pulp Fiction" et "Kill Bill" ?',
                'reponse1' => 'Quentin Tarantino',
                'reponse2' => 'Martin Scorsese',
                'reponse3' => 'Guy Ritchie',
                'reponse4' => 'Brian De Palma',
                'reponse5' => 'Francis Ford Coppola',
                'reponse6' => 'David Lynch',
                'reponse7' => 'Wes Anderson',
                'reponse8' => 'Tim Burton',
                'reponse9' => 'Oliver Stone',
                'reponse10' => 'Paul Thomas Anderson',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel acteur interprète le rôle de Neo dans la saga "Matrix" ?',
                'reponse1' => 'Keanu Reeves',
                'reponse2' => 'Laurence Fishburne',
                'reponse3' => 'Hugo Weaving',
                'reponse4' => 'Matt Damon',
                'reponse5' => 'Leonardo DiCaprio',
                'reponse6' => 'Will Smith',
                'reponse7' => 'Tom Cruise',
                'reponse8' => 'Christian Bale',
                'reponse9' => 'Ethan Hawke',
                'reponse10' => 'Edward Norton',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel film a reçu la Palme d\'or au Festival de Cannes 2019 avant de triompher aux Oscars ?',
                'reponse1' => 'Parasite',
                'reponse2' => 'Once Upon a Time in Hollywood',
                'reponse3' => 'Portrait de la jeune fille en feu',
                'reponse4' => '1917',
                'reponse5' => 'Joker',
                'reponse6' => 'The Irishman',
                'reponse7' => 'Green Book',
                'reponse8' => 'Roma',
                'reponse9' => 'Anatomie d\'une chute',
                'reponse10' => 'Drive',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Quel est le premier long-métrage d\'animation des studios Pixar sorti en 1995 ?',
                'reponse1' => 'Toy Story',
                'reponse2' => '1001 Pattes',
                'reponse3' => 'Monstres et Cie',
                'reponse4' => 'Le Monde de Nemo',
                'reponse5' => 'Cars',
                'reponse6' => 'Les Indestructibles',
                'reponse7' => 'Fourmiz',
                'reponse8' => 'Shrek',
                'reponse9' => 'L\'Âge de glace',
                'reponse10' => 'Tarzan',
            ],
            [
                'categorie' => 'Cinéma',
                'question' => 'Dans la saga Harry Potter, quel acteur prête ses traits au professeur Severus Rogue ?',
                'reponse1' => 'Alan Rickman',
                'reponse2' => 'Michael Gambon',
                'reponse3' => 'Gary Oldman',
                'reponse4' => 'Ralph Fiennes',
                'reponse5' => 'Maggie Smith',
                'reponse6' => 'David Thewlis',
                'reponse7' => 'Jason Isaacs',
                'reponse8' => 'Kenneth Branagh',
                'reponse9' => 'Richard Harris',
                'reponse10' => 'Ian McKellen',
            ],

            // =========================================================
            // SPORT (10 questions)
            // =========================================================
            [
                'categorie' => 'Sport',
                'question' => 'Quel pays a remporté la Coupe du Monde de football en 2018 ?',
                'reponse1' => 'France',
                'reponse2' => 'Croatie',
                'reponse3' => 'Brésil',
                'reponse4' => 'Allemagne',
                'reponse5' => 'Argentine',
                'reponse6' => 'Espagne',
                'reponse7' => 'Belgique',
                'reponse8' => 'Angleterre',
                'reponse9' => 'Portugal',
                'reponse10' => 'Italie',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Combien de titres du Grand Chelem Rafael Nadal a-t-il remportés à Roland-Garros ?',
                'reponse1' => '14',
                'reponse2' => '12',
                'reponse3' => '10',
                'reponse4' => '15',
                'reponse5' => '11',
                'reponse6' => '13',
                'reponse7' => '9',
                'reponse8' => '16',
                'reponse9' => '8',
                'reponse10' => '7',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Quelle distance mesure un marathon officiel ?',
                'reponse1' => '42,195 km',
                'reponse2' => '40,000 km',
                'reponse3' => '45,250 km',
                'reponse4' => '50,000 km',
                'reponse5' => '41,500 km',
                'reponse6' => '43,000 km',
                'reponse7' => '38,195 km',
                'reponse8' => '42,000 km',
                'reponse9' => '44,195 km',
                'reponse10' => '46,200 km',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Quel joueur de basketball détient le record du plus grand nombre de points en NBA ?',
                'reponse1' => 'LeBron James',
                'reponse2' => 'Kareem Abdul-Jabbar',
                'reponse3' => 'Michael Jordan',
                'reponse4' => 'Kobe Bryant',
                'reponse5' => 'Karl Malone',
                'reponse6' => 'Shaquille O\'Neal',
                'reponse7' => 'Wilt Chamberlain',
                'reponse8' => 'Stephen Curry',
                'reponse9' => 'Magic Johnson',
                'reponse10' => 'Larry Bird',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Dans quel sport utilise-t-on un volant ?',
                'reponse1' => 'Badminton',
                'reponse2' => 'Tennis',
                'reponse3' => 'Squash',
                'reponse4' => 'Tennis de table',
                'reponse5' => 'Padel',
                'reponse6' => 'Pelote basque',
                'reponse7' => 'Cricket',
                'reponse8' => 'Golf',
                'reponse9' => 'Baseball',
                'reponse10' => 'Volleyball',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Quel pays détient le record du plus grand nombre de victoires en Coupe du Monde de football masculin ?',
                'reponse1' => 'Brésil',
                'reponse2' => 'Allemagne',
                'reponse3' => 'Italie',
                'reponse4' => 'Argentine',
                'reponse5' => 'France',
                'reponse6' => 'Uruguay',
                'reponse7' => 'Angleterre',
                'reponse8' => 'Espagne',
                'reponse9' => 'Pays-Bas',
                'reponse10' => 'Portugal',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Combien de joueurs composent une équipe de rugby à XV sur le terrain ?',
                'reponse1' => '15',
                'reponse2' => '13',
                'reponse3' => '11',
                'reponse4' => '7',
                'reponse5' => '12',
                'reponse6' => '14',
                'reponse7' => '16',
                'reponse8' => '10',
                'reponse9' => '18',
                'reponse10' => '9',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Combien de Ballons d\'Or Lionel Messi a-t-il remportés au cours de sa carrière ?',
                'reponse1' => '8',
                'reponse2' => '5',
                'reponse3' => '7',
                'reponse4' => '6',
                'reponse5' => '9',
                'reponse6' => '4',
                'reponse7' => '3',
                'reponse8' => '10',
                'reponse9' => '2',
                'reponse10' => '1',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Qui détient le record du monde du 100 mètres en athlétisme (9,58 s) ?',
                'reponse1' => 'Usain Bolt',
                'reponse2' => 'Tyson Gay',
                'reponse3' => 'Yohan Blake',
                'reponse4' => 'Carl Lewis',
                'reponse5' => 'Asafa Powell',
                'reponse6' => 'Justin Gatlin',
                'reponse7' => 'Maurice Greene',
                'reponse8' => 'Noah Lyles',
                'reponse9' => 'Christian Coleman',
                'reponse10' => 'Linford Christie',
            ],
            [
                'categorie' => 'Sport',
                'question' => 'Quelle ville a accueilli les Jeux Olympiques d\'été en 2024 ?',
                'reponse1' => 'Paris',
                'reponse2' => 'Tokyo',
                'reponse3' => 'Londres',
                'reponse4' => 'Los Angeles',
                'reponse5' => 'Rio de Janeiro',
                'reponse6' => 'Madrid',
                'reponse7' => 'Rome',
                'reponse8' => 'Berlin',
                'reponse9' => 'Sydney',
                'reponse10' => 'Pékin',
            ],

            // =========================================================
            // GÉOGRAPHIE (10 questions)
            // =========================================================
            [
                'categorie' => 'Géographie',
                'question' => 'Quelle est la capitale de l\'Australie ?',
                'reponse1' => 'Canberra',
                'reponse2' => 'Sydney',
                'reponse3' => 'Melbourne',
                'reponse4' => 'Brisbane',
                'reponse5' => 'Perth',
                'reponse6' => 'Adélaïde',
                'reponse7' => 'Auckland',
                'reponse8' => 'Wellington',
                'reponse9' => 'Darwin',
                'reponse10' => 'Hobart',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel est le plus grand océan de la planète ?',
                'reponse1' => 'Océan Pacifique',
                'reponse2' => 'Océan Atlantique',
                'reponse3' => 'Océan Indien',
                'reponse4' => 'Océan Arctique',
                'reponse5' => 'Océan Austral',
                'reponse6' => 'Mer Méditerranée',
                'reponse7' => 'Mer Rouge',
                'reponse8' => 'Mer des Caraïbes',
                'reponse9' => 'Mer Baltique',
                'reponse10' => 'Mer de Chine',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel pays possède la plus grande superficie au monde ?',
                'reponse1' => 'Russie',
                'reponse2' => 'Canada',
                'reponse3' => 'Chine',
                'reponse4' => 'États-Unis',
                'reponse5' => 'Brésil',
                'reponse6' => 'Australie',
                'reponse7' => 'Inde',
                'reponse8' => 'Argentine',
                'reponse9' => 'Kazakhstan',
                'reponse10' => 'Algérie',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel est le plus haut sommet du monde culminant à 8 848 mètres ?',
                'reponse1' => 'Mont Everest',
                'reponse2' => 'K2',
                'reponse3' => 'Kangchenjunga',
                'reponse4' => 'Mont Blanc',
                'reponse5' => 'Kilimandjaro',
                'reponse6' => 'Makalu',
                'reponse7' => 'Annapurna',
                'reponse8' => 'Aconcagua',
                'reponse9' => 'Mont McKinley (Denali)',
                'reponse10' => 'Lhotse',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quelle est la capitale officielle du Canada ?',
                'reponse1' => 'Ottawa',
                'reponse2' => 'Toronto',
                'reponse3' => 'Montréal',
                'reponse4' => 'Vancouver',
                'reponse5' => 'Québec',
                'reponse6' => 'Calgary',
                'reponse7' => 'Edmonton',
                'reponse8' => 'Winnipeg',
                'reponse9' => 'Halifax',
                'reponse10' => 'Victoria',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel fleuve traverse la ville de Londres ?',
                'reponse1' => 'La Tamise',
                'reponse2' => 'La Seine',
                'reponse3' => 'Le Danube',
                'reponse4' => 'Le Rhin',
                'reponse5' => 'Le Tibre',
                'reponse6' => 'L\'Elbe',
                'reponse7' => 'Le Tage',
                'reponse8' => 'La Volga',
                'reponse9' => 'Le Pô',
                'reponse10' => 'La Mersey',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel détroit sépare l\'Europe (Espagne) du continent africain (Maroc) ?',
                'reponse1' => 'Détroit de Gibraltar',
                'reponse2' => 'Détroit du Bosphore',
                'reponse3' => 'Détroit d\'Ormuz',
                'reponse4' => 'Détroit de Malacca',
                'reponse5' => 'Détroit de Béring',
                'reponse6' => 'Détroit des Dardanelles',
                'reponse7' => 'Détroit de Messine',
                'reponse8' => 'Détroit de Magellan',
                'reponse9' => 'Canal de Suez',
                'reponse10' => 'Canal de Panama',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quel est le plus grand désert chaud de la planète ?',
                'reponse1' => 'Désert du Sahara',
                'reponse2' => 'Désert de Gobi',
                'reponse3' => 'Désert du Kalahari',
                'reponse4' => 'Désert d\'Atacama',
                'reponse5' => 'Désert de Mojave',
                'reponse6' => 'Désert de Namib',
                'reponse7' => 'Désert de Sonora',
                'reponse8' => 'Grand Désert de Sable',
                'reponse9' => 'Désert de Simpson',
                'reponse10' => 'Désert de Thar',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Quelle est la capitale du Japon ?',
                'reponse1' => 'Tokyo',
                'reponse2' => 'Kyoto',
                'reponse3' => 'Osaka',
                'reponse4' => 'Yokohama',
                'reponse5' => 'Hiroshima',
                'reponse6' => 'Sapporo',
                'reponse7' => 'Nagoya',
                'reponse8' => 'Kobe',
                'reponse9' => 'Fukuoka',
                'reponse10' => 'Séoul',
            ],
            [
                'categorie' => 'Géographie',
                'question' => 'Sur quel continent se trouve le lac Victoria ?',
                'reponse1' => 'Afrique',
                'reponse2' => 'Asie',
                'reponse3' => 'Amérique du Sud',
                'reponse4' => 'Océanie',
                'reponse5' => 'Europe',
                'reponse6' => 'Amérique du Nord',
                'reponse7' => 'Antarctique',
                'reponse8' => 'Moyen-Orient',
                'reponse9' => 'Eurasie',
                'reponse10' => 'Scandinavie',
            ],

            // =========================================================
            // SCIENCES (10 questions)
            // =========================================================
            [
                'categorie' => 'Sciences',
                'question' => 'Quel est le symbole chimique de l\'or ?',
                'reponse1' => 'Au',
                'reponse2' => 'Ag',
                'reponse3' => 'Fe',
                'reponse4' => 'Cu',
                'reponse5' => 'Pb',
                'reponse6' => 'Or',
                'reponse7' => 'Pt',
                'reponse8' => 'Zn',
                'reponse9' => 'Hg',
                'reponse10' => 'Sn',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quelle planète du système solaire est la plus proche du Soleil ?',
                'reponse1' => 'Mercure',
                'reponse2' => 'Vénus',
                'reponse3' => 'Mars',
                'reponse4' => 'Jupiter',
                'reponse5' => 'Saturne',
                'reponse6' => 'Uranus',
                'reponse7' => 'Neptune',
                'reponse8' => 'Pluton',
                'reponse9' => 'Terre',
                'reponse10' => 'Cérès',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quelle est la formule chimique de l\'eau ?',
                'reponse1' => 'H2O',
                'reponse2' => 'CO2',
                'reponse3' => 'NaCl',
                'reponse4' => 'CH4',
                'reponse5' => 'O2',
                'reponse6' => 'H2O2',
                'reponse7' => 'NH3',
                'reponse8' => 'C6H12O6',
                'reponse9' => 'HCl',
                'reponse10' => 'H2SO4',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'À quelle vitesse approximative la lumière se déplace-t-elle dans le vide ?',
                'reponse1' => '300 000 km/s',
                'reponse2' => '150 000 km/s',
                'reponse3' => '1 000 000 km/s',
                'reponse4' => '30 000 km/s',
                'reponse5' => '340 m/s',
                'reponse6' => '500 000 km/s',
                'reponse7' => '100 000 km/s',
                'reponse8' => '750 000 km/s',
                'reponse9' => '10 000 km/s',
                'reponse10' => '3 000 km/s',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quel célèbre physicien a formulé la théorie de la Relativité générale ?',
                'reponse1' => 'Albert Einstein',
                'reponse2' => 'Isaac Newton',
                'reponse3' => 'Niels Bohr',
                'reponse4' => 'Galilée',
                'reponse5' => 'Stephen Hawking',
                'reponse6' => 'Nikola Tesla',
                'reponse7' => 'Max Planck',
                'reponse8' => 'Marie Curie',
                'reponse9' => 'Louis Pasteur',
                'reponse10' => 'Johannes Kepler',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quel gaz compose la majeure partie (environ 78 %) de l\'atmosphère terrestre ?',
                'reponse1' => 'Azote (Diazote)',
                'reponse2' => 'Oxygène',
                'reponse3' => 'Dioxyde de carbone',
                'reponse4' => 'Argon',
                'reponse5' => 'Hydrogène',
                'reponse6' => 'Hélium',
                'reponse7' => 'Méthane',
                'reponse8' => 'Néon',
                'reponse9' => 'Ozone',
                'reponse10' => 'Monoxyde de carbone',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quelle est l\'unité de mesure officielle de la force dans le Système International ?',
                'reponse1' => 'Newton (N)',
                'reponse2' => 'Joule (J)',
                'reponse3' => 'Watt (W)',
                'reponse4' => 'Pascal (Pa)',
                'reponse5' => 'Volt (V)',
                'reponse6' => 'Ampère (A)',
                'reponse7' => 'Tesla (T)',
                'reponse8' => 'Hertz (Hz)',
                'reponse9' => 'Kelvin (K)',
                'reponse10' => 'Ohm (Ω)',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Quelles cellules sanguines sont principalement chargées de transporter l\'oxygène dans le corps ?',
                'reponse1' => 'Les globules rouges (hématies)',
                'reponse2' => 'Les globules blancs (leucocytes)',
                'reponse3' => 'Les plaquettes sanguines',
                'reponse4' => 'Les neurones',
                'reponse5' => 'Les lymphocytes T',
                'reponse6' => 'Les ostéocytes',
                'reponse7' => 'Les cellules souches',
                'reponse8' => 'Les adipocytes',
                'reponse9' => 'Les plasmocytes',
                'reponse10' => 'Les monocytes',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'À quelle température l\'eau pure gèle-t-elle à pression atmosphérique normale ?',
                'reponse1' => '0 °C',
                'reponse2' => '-10 °C',
                'reponse3' => '4 °C',
                'reponse4' => '-5 °C',
                'reponse5' => '32 °C',
                'reponse6' => '-1 °C',
                'reponse7' => '10 °C',
                'reponse8' => '-20 °C',
                'reponse9' => '100 °C',
                'reponse10' => '-273 °C',
            ],
            [
                'categorie' => 'Sciences',
                'question' => 'Combien de paires de chromosomes une cellule humaine normale contient-elle ?',
                'reponse1' => '23 paires',
                'reponse2' => '46 paires',
                'reponse3' => '21 paires',
                'reponse4' => '24 paires',
                'reponse5' => '12 paires',
                'reponse6' => '22 paires',
                'reponse7' => '20 paires',
                'reponse8' => '25 paires',
                'reponse9' => '18 paires',
                'reponse10' => '30 paires',
            ],
        ];

        foreach ($questions as $q) {
            Question::create($q);
        }
    }
}
