<?php

namespace Database\Seeders;

use App\Models\Categorie;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Remplit la base avec 144 vraies questions de sport captivantes,
     * réparties équitablement entre les 4 catégories et les 3 niveaux.
     */
    public function run(): void
    {
        Question::truncate();

        $categories = Categorie::pluck('id', 'slug')->toArray();
        $now = now();

        $questions = [
            // ==========================================
            // FOOTBALL (slug: foot)
            // ==========================================
            // --- Facile ---
            [
                'slug' => 'foot',
                'question' => 'Quel pays a remporté la Coupe du Monde de football en 2018 ?',
                'bonne_reponse' => 'France',
                'mauvaise_1' => 'Croatie',
                'mauvaise_2' => 'Brésil',
                'mauvaise_3' => 'Allemagne',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur français a remporté le Ballon d\'Or en 1998 ?',
                'bonne_reponse' => 'Zinédine Zidane',
                'mauvaise_1' => 'Thierry Henry',
                'mauvaise_2' => 'Didier Deschamps',
                'mauvaise_3' => 'David Trezeguet',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Combien de joueurs d\'une même équipe sont présents sur le terrain au coup d\'envoi ?',
                'bonne_reponse' => '11',
                'mauvaise_1' => '10',
                'mauvaise_2' => '12',
                'mauvaise_3' => '9',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel club espagnol a remporté le plus grand nombre de Ligues des Champions ?',
                'bonne_reponse' => 'Real Madrid',
                'mauvaise_1' => 'FC Barcelone',
                'mauvaise_2' => 'Atlético Madrid',
                'mauvaise_3' => 'Séville FC',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Dans quel club anglais Erling Haaland a-t-il battu le record de buts en une saison ?',
                'bonne_reponse' => 'Manchester City',
                'mauvaise_1' => 'Manchester United',
                'mauvaise_2' => 'Liverpool',
                'mauvaise_3' => 'Chelsea',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur argentin a guidé son pays au titre mondial en 2022 au Qatar ?',
                'bonne_reponse' => 'Lionel Messi',
                'mauvaise_1' => 'Angel Di Maria',
                'mauvaise_2' => 'Sergio Agüero',
                'mauvaise_3' => 'Paulo Dybala',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'De quelle couleur est le carton qui expulse directement un joueur du terrain ?',
                'bonne_reponse' => 'Rouge',
                'mauvaise_1' => 'Jaune',
                'mauvaise_2' => 'Blanc',
                'mauvaise_3' => 'Noir',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Dans quel club Kylian Mbappé a-t-il signé à l\'été 2024 ?',
                'bonne_reponse' => 'Real Madrid',
                'mauvaise_1' => 'Bayern Munich',
                'mauvaise_2' => 'Arsenal',
                'mauvaise_3' => 'Juventus',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quelle sélection nationale est surnommée la « Seleção » ?',
                'bonne_reponse' => 'Le Brésil',
                'mauvaise_1' => 'L\'Argentine',
                'mauvaise_2' => 'L\'Espagne',
                'mauvaise_3' => 'L\'Italie',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Combien de temps dure un match de football réglementaire hors temps additionnel ?',
                'bonne_reponse' => '90 minutes',
                'mauvaise_1' => '80 minutes',
                'mauvaise_2' => '100 minutes',
                'mauvaise_3' => '70 minutes',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel club français est le seul à avoir remporté la Ligue des Champions (en 1993) ?',
                'bonne_reponse' => 'Olympique de Marseille',
                'mauvaise_1' => 'Paris Saint-Germain',
                'mauvaise_2' => 'AS Monaco',
                'mauvaise_3' => 'Olympique Lyonnais',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur est le seul autorisé à utiliser ses mains dans sa surface de réparation ?',
                'bonne_reponse' => 'Le gardien de but',
                'mauvaise_1' => 'Le capitaine',
                'mauvaise_2' => 'Le défenseur central',
                'mauvaise_3' => 'L\'avant-centre',
                'difficulte' => 'facile',
            ],

            // --- Moyen ---
            [
                'slug' => 'foot',
                'question' => 'Quel attaquant portugais a remporté 5 Ballons d\'Or au cours de sa carrière ?',
                'bonne_reponse' => 'Cristiano Ronaldo',
                'mauvaise_1' => 'Luís Figo',
                'mauvaise_2' => 'Eusébio',
                'mauvaise_3' => 'Deco',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'En quelle année l\'équipe de France a-t-elle remporté sa première Coupe du Monde ?',
                'bonne_reponse' => '1998',
                'mauvaise_1' => '1984',
                'mauvaise_2' => '2006',
                'mauvaise_3' => '1994',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel entraîneur français a mené le Real Madrid à 3 sacres consécutifs en Ligue des Champions (2016-2018) ?',
                'bonne_reponse' => 'Zinédine Zidane',
                'mauvaise_1' => 'Didier Deschamps',
                'mauvaise_2' => 'Arsène Wenger',
                'mauvaise_3' => 'Laurent Blanc',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel pays a remporté l\'Euro 2024 de football disputé en Allemagne ?',
                'bonne_reponse' => 'Espagne',
                'mauvaise_1' => 'Angleterre',
                'mauvaise_2' => 'France',
                'mauvaise_3' => 'Pays-Bas',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur détient le record du transfert le plus onéreux de l\'histoire (222 M€) ?',
                'bonne_reponse' => 'Neymar',
                'mauvaise_1' => 'Kylian Mbappé',
                'mauvaise_2' => 'Philippe Coutinho',
                'mauvaise_3' => 'Paul Pogba',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel club italien est surnommé la « Vieille Dame » ou les « Bianconeri » ?',
                'bonne_reponse' => 'Juventus',
                'mauvaise_1' => 'AC Milan',
                'mauvaise_2' => 'Inter Milan',
                'mauvaise_3' => 'AS Rome',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Qui est le meilleur buteur de l\'histoire de l\'équipe de France masculine ?',
                'bonne_reponse' => 'Olivier Giroud',
                'mauvaise_1' => 'Thierry Henry',
                'mauvaise_2' => 'Antoine Griezmann',
                'mauvaise_3' => 'Michel Platini',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel gardien italien a été champion du monde en 2006 et a disputé plus de 1 000 matches ?',
                'bonne_reponse' => 'Gianluigi Buffon',
                'mauvaise_1' => 'Dino Zoff',
                'mauvaise_2' => 'Francesco Toldo',
                'mauvaise_3' => 'Walter Zenga',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel stade emblématique est le domicile du club de Liverpool FC ?',
                'bonne_reponse' => 'Anfield',
                'mauvaise_1' => 'Old Trafford',
                'mauvaise_2' => 'Etihad Stadium',
                'mauvaise_3' => 'Stamford Bridge',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel prix récompense chaque année le plus beau but inscrit au monde ?',
                'bonne_reponse' => 'Prix Puskás',
                'mauvaise_1' => 'Trophée Kopa',
                'mauvaise_2' => 'Trophée Yachine',
                'mauvaise_3' => 'Soulier d\'Or',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel attaquant polonais a empilé les buts au Bayern Munich puis au FC Barcelone ?',
                'bonne_reponse' => 'Robert Lewandowski',
                'mauvaise_1' => 'Miroslav Klose',
                'mauvaise_2' => 'Mario Mandžukić',
                'mauvaise_3' => 'Luka Jović',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'foot',
                'question' => 'Dans quelle ville se trouve le stade mythique de San Siro (Giuseppe Meazza) ?',
                'bonne_reponse' => 'Milan',
                'mauvaise_1' => 'Rome',
                'mauvaise_2' => 'Turin',
                'mauvaise_3' => 'Naples',
                'difficulte' => 'moyen',
            ],

            // --- Difficile ---
            [
                'slug' => 'foot',
                'question' => 'Quel pays a remporté la toute première Coupe du Monde de football en 1930 ?',
                'bonne_reponse' => 'Uruguay',
                'mauvaise_1' => 'Argentine',
                'mauvaise_2' => 'Brésil',
                'mauvaise_3' => 'Italie',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel club a créé l\'exploit en devenant champion d\'Angleterre en 2016 avec Claudio Ranieri ?',
                'bonne_reponse' => 'Leicester City',
                'mauvaise_1' => 'Blackburn Rovers',
                'mauvaise_2' => 'Wolverhampton',
                'mauvaise_3' => 'Southampton',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur africain a été le premier à remporter le Ballon d\'Or en 1995 ?',
                'bonne_reponse' => 'George Weah',
                'mauvaise_1' => 'Samuel Eto\'o',
                'mauvaise_2' => 'Didier Drogba',
                'mauvaise_3' => 'Roger Milla',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel gardien soviétique est le seul portier de l\'histoire à avoir gagné le Ballon d\'Or (1963) ?',
                'bonne_reponse' => 'Lev Yachine',
                'mauvaise_1' => 'Dino Zoff',
                'mauvaise_2' => 'Gordon Banks',
                'mauvaise_3' => 'Sepp Maier',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur détient le record absolu de buts sur une seule édition de Coupe du Monde (13 buts en 1958) ?',
                'bonne_reponse' => 'Just Fontaine',
                'mauvaise_1' => 'Pelé',
                'mauvaise_2' => 'Gerd Müller',
                'mauvaise_3' => 'Eusébio',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur allemand a inscrit le but de la victoire en prolongation de la finale du Mondial 2014 ?',
                'bonne_reponse' => 'Mario Götze',
                'mauvaise_1' => 'André Schürrle',
                'mauvaise_2' => 'Mesut Özil',
                'mauvaise_3' => 'Toni Kroos',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'En quelle année le Paris Saint-Germain a-t-il remporté la Coupe d\'Europe des Vainqueurs de Coupe (C2) ?',
                'bonne_reponse' => '1996',
                'mauvaise_1' => '1993',
                'mauvaise_2' => '1998',
                'mauvaise_3' => '2001',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel club a remporté la toute première Coupe d\'Europe des Clubs Champions en 1956 face à Reims ?',
                'bonne_reponse' => 'Real Madrid',
                'mauvaise_1' => 'Benfica',
                'mauvaise_2' => 'AC Milan',
                'mauvaise_3' => 'Inter Milan',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur a réussi un triplé en finale de la Coupe du Monde 1966 avec l\'Angleterre ?',
                'bonne_reponse' => 'Geoff Hurst',
                'mauvaise_1' => 'Bobby Charlton',
                'mauvaise_2' => 'Bobby Moore',
                'mauvaise_3' => 'Jimmy Greaves',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel joueur détient le record du plus grand nombre d\'apparitions en phase finale de Coupe du Monde (26 matches) ?',
                'bonne_reponse' => 'Lionel Messi',
                'mauvaise_1' => 'Lothar Matthäus',
                'mauvaise_2' => 'Miroslav Klose',
                'mauvaise_3' => 'Paolo Maldini',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Quel entraîneur a mené la Grèce à la victoire surprise lors de l\'Euro 2004 ?',
                'bonne_reponse' => 'Otto Rehhagel',
                'mauvaise_1' => 'Guus Hiddink',
                'mauvaise_2' => 'Dick Advocaat',
                'mauvaise_3' => 'Luiz Felipe Scolari',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'foot',
                'question' => 'Qui était le capitaine de l\'équipe de France lors de la victoire à l\'Euro 1984 ?',
                'bonne_reponse' => 'Michel Platini',
                'mauvaise_1' => 'Alain Giresse',
                'mauvaise_2' => 'Jean Tigana',
                'mauvaise_3' => 'Maxime Bossis',
                'difficulte' => 'difficile',
            ],

            // ==========================================
            // BASKET (slug: basket)
            // ==========================================
            // --- Facile ---
            [
                'slug' => 'basket',
                'question' => 'Avec quelle franchise Michael Jordan a-t-il conquis ses 6 titres de champion NBA ?',
                'bonne_reponse' => 'Chicago Bulls',
                'mauvaise_1' => 'Los Angeles Lakers',
                'mauvaise_2' => 'Boston Celtics',
                'mauvaise_3' => 'Miami Heat',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Combien de points vaut un tir réussi au-delà de la ligne des 6,75 m (ou 7,24 m en NBA) ?',
                'bonne_reponse' => '3 points',
                'mauvaise_1' => '2 points',
                'mauvaise_2' => '1 point',
                'mauvaise_3' => '4 points',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel joueur surnommé « King James » est devenu le meilleur marqueur de l\'histoire de la NBA ?',
                'bonne_reponse' => 'LeBron James',
                'mauvaise_1' => 'Kobe Bryant',
                'mauvaise_2' => 'Kevin Durant',
                'mauvaise_3' => 'Shaquille O\'Neal',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Combien de joueurs par équipe sont simultanément sur le parquet lors d\'un match de basket ?',
                'bonne_reponse' => '5',
                'mauvaise_1' => '6',
                'mauvaise_2' => '4',
                'mauvaise_3' => '7',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel géant français (2m22) a été choisi en 1ère position de la draft NBA 2023 par San Antonio ?',
                'bonne_reponse' => 'Victor Wembanyama',
                'mauvaise_1' => 'Bilal Coulibaly',
                'mauvaise_2' => 'Alexandre Sarr',
                'mauvaise_3' => 'Zaccharie Risacher',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'À quelle hauteur réglementaire se situe l\'arceau d\'un panier de basket ?',
                'bonne_reponse' => '3,05 mètres',
                'mauvaise_1' => '2,80 mètres',
                'mauvaise_2' => '3,25 mètres',
                'mauvaise_3' => '3,50 mètres',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel geste spectaculaire consiste à claquer directement le ballon dans l\'arceau ?',
                'bonne_reponse' => 'Le dunk',
                'mauvaise_1' => 'Le layup',
                'mauvaise_2' => 'Le fadeaway',
                'mauvaise_3' => 'Le cross-over',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel meneur des Warriors est considéré comme le plus grand shooteur à 3 points de l\'histoire ?',
                'bonne_reponse' => 'Stephen Curry',
                'mauvaise_1' => 'Klay Thompson',
                'mauvaise_2' => 'Ray Allen',
                'mauvaise_3' => 'Reggie Miller',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Combien de points rapporte un lancer franc réussi ?',
                'bonne_reponse' => '1 point',
                'mauvaise_1' => '2 points',
                'mauvaise_2' => '3 points',
                'mauvaise_3' => '0,5 point',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle franchise NBA joue dans la mythique salle du Madison Square Garden à New York ?',
                'bonne_reponse' => 'New York Knicks',
                'mauvaise_1' => 'Brooklyn Nets',
                'mauvaise_2' => 'Boston Celtics',
                'mauvaise_3' => 'Philadelphia 76ers',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle infraction commet un joueur qui se déplace sans faire rebondir le ballon ?',
                'bonne_reponse' => 'Le marcher',
                'mauvaise_1' => 'La reprise de dribble',
                'mauvaise_2' => 'Le passage en force',
                'mauvaise_3' => 'Le pied',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle est la durée réglementaire d\'un quart-temps en NBA ?',
                'bonne_reponse' => '12 minutes',
                'mauvaise_1' => '10 minutes',
                'mauvaise_2' => '15 minutes',
                'mauvaise_3' => '8 minutes',
                'difficulte' => 'facile',
            ],

            // --- Moyen ---
            [
                'slug' => 'basket',
                'question' => 'Quel meneur français a remporté 4 bagues NBA avec les Spurs et a été MVP des Finales en 2007 ?',
                'bonne_reponse' => 'Tony Parker',
                'mauvaise_1' => 'Boris Diaw',
                'mauvaise_2' => 'Nicolas Batum',
                'mauvaise_3' => 'Evan Fournier',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'De combien de secondes dispose une équipe en NBA pour tenter un tir au panier ?',
                'bonne_reponse' => '24 secondes',
                'mauvaise_1' => '30 secondes',
                'mauvaise_2' => '20 secondes',
                'mauvaise_3' => '14 secondes',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel pivot ultra-dominant a formé un tandem légendaire avec Kobe Bryant aux Lakers (2000-2002) ?',
                'bonne_reponse' => 'Shaquille O\'Neal',
                'mauvaise_1' => 'Patrick Ewing',
                'mauvaise_2' => 'Hakeem Olajuwon',
                'mauvaise_3' => 'David Robinson',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel joueur grec surnommé « The Greek Freak » a été champion NBA avec les Bucks en 2021 ?',
                'bonne_reponse' => 'Giannis Antetokounmpo',
                'mauvaise_1' => 'Luka Dončić',
                'mauvaise_2' => 'Nikola Jokić',
                'mauvaise_3' => 'Kristaps Porziņģis',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel pivot tricolore a été élu 4 fois Meilleur Défenseur de l\'année en NBA (DPOY) ?',
                'bonne_reponse' => 'Rudy Gobert',
                'mauvaise_1' => 'Joakim Noah',
                'mauvaise_2' => 'Victor Wembanyama',
                'mauvaise_3' => 'Clint Capela',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel surnom a été donné à l\'équipe américaine des Jeux Olympiques de Barcelone en 1992 ?',
                'bonne_reponse' => 'Dream Team',
                'mauvaise_1' => 'Redeem Team',
                'mauvaise_2' => 'Avengers',
                'mauvaise_3' => 'All-Stars',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel pivot serbe des Denver Nuggets a été élu triple MVP de la saison régulière en NBA ?',
                'bonne_reponse' => 'Nikola Jokić',
                'mauvaise_1' => 'Nikola Vučević',
                'mauvaise_2' => 'Jusuf Nurkić',
                'mauvaise_3' => 'Boban Marjanović',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Combien de fautes personnelles provoquent l\'expulsion d\'un joueur lors d\'une rencontre NBA ?',
                'bonne_reponse' => '6 fautes',
                'mauvaise_1' => '5 fautes',
                'mauvaise_2' => '4 fautes',
                'mauvaise_3' => '7 fautes',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel numéro mythique Kobe Bryant a-t-il endossé aux Lakers en plus du numéro 8 ?',
                'bonne_reponse' => '24',
                'mauvaise_1' => '23',
                'mauvaise_2' => '33',
                'mauvaise_3' => '10',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel coach mythique a décroché 11 bagues NBA avec les Bulls de Jordan et les Lakers de Kobe ?',
                'bonne_reponse' => 'Phil Jackson',
                'mauvaise_1' => 'Gregg Popovich',
                'mauvaise_2' => 'Pat Riley',
                'mauvaise_3' => 'Steve Kerr',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel meneur superstar slovène fait le bonheur des Dallas Mavericks ?',
                'bonne_reponse' => 'Luka Dončić',
                'mauvaise_1' => 'Goran Dragić',
                'mauvaise_2' => 'Bogdan Bogdanović',
                'mauvaise_3' => 'Deni Avdija',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle franchise partage avec les Lakers le record du plus grand nombre de titres de champion NBA ?',
                'bonne_reponse' => 'Boston Celtics',
                'mauvaise_1' => 'Golden State Warriors',
                'mauvaise_2' => 'Chicago Bulls',
                'mauvaise_3' => 'San Antonio Spurs',
                'difficulte' => 'moyen',
            ],

            // --- Difficile ---
            [
                'slug' => 'basket',
                'question' => 'Quel joueur détient le record absolu du plus grand nombre de points en un match NBA (100 pts en 1962) ?',
                'bonne_reponse' => 'Wilt Chamberlain',
                'mauvaise_1' => 'Bill Russell',
                'mauvaise_2' => 'Kareem Abdul-Jabbar',
                'mauvaise_3' => 'Elgin Baylor',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle légende des Boston Celtics a remporté 11 bagues de champion NBA comme joueur dans les années 50-60 ?',
                'bonne_reponse' => 'Bill Russell',
                'mauvaise_1' => 'Larry Bird',
                'mauvaise_2' => 'John Havlicek',
                'mauvaise_3' => 'Bob Cousy',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel professeur canadien a inventé le sport du basketball en 1891 ?',
                'bonne_reponse' => 'James Naismith',
                'mauvaise_1' => 'William Morgan',
                'mauvaise_2' => 'Walter Camp',
                'mauvaise_3' => 'Abner Doubleday',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel meneur légendaire du Utah Jazz détient le record de passes décisives en carrière NBA ?',
                'bonne_reponse' => 'John Stockton',
                'mauvaise_1' => 'Jason Kidd',
                'mauvaise_2' => 'Magic Johnson',
                'mauvaise_3' => 'Chris Paul',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quelle franchise canadienne est devenue la première équipe non-américaine sacrée championne NBA (en 2019) ?',
                'bonne_reponse' => 'Toronto Raptors',
                'mauvaise_1' => 'Vancouver Grizzlies',
                'mauvaise_2' => 'Montreal Royals',
                'mauvaise_3' => 'Calgary Flames',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'En quelle année l\'équipe de France masculine a-t-elle remporté son unique titre européen (EuroBasket) ?',
                'bonne_reponse' => '2013',
                'mauvaise_1' => '2011',
                'mauvaise_2' => '2005',
                'mauvaise_3' => '2015',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel joueur a été la silhouette qui a inspiré le logo officiel de la NBA ?',
                'bonne_reponse' => 'Jerry West',
                'mauvaise_1' => 'Michael Jordan',
                'mauvaise_2' => 'Oscar Robertson',
                'mauvaise_3' => 'Julius Erving',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel joueur a été élu MVP des Finales NBA 2014 sous le maillot des San Antonio Spurs ?',
                'bonne_reponse' => 'Kawhi Leonard',
                'mauvaise_1' => 'Tim Duncan',
                'mauvaise_2' => 'Tony Parker',
                'mauvaise_3' => 'Manu Ginóbili',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel record de victoires sur une seule saison régulière les Warriors ont-ils signé en 2015-2016 ?',
                'bonne_reponse' => '73 victoires',
                'mauvaise_1' => '72 victoires',
                'mauvaise_2' => '70 victoires',
                'mauvaise_3' => '75 victoires',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel joueur a rentré le tir à 3 points décisif dans la dernière minute du Game 7 des Finales 2016 pour Cleveland ?',
                'bonne_reponse' => 'Kyrie Irving',
                'mauvaise_1' => 'JR Smith',
                'mauvaise_2' => 'Kevin Love',
                'mauvaise_3' => 'LeBron James',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel pivot dominicain a mené les Boston Celtics au titre NBA en 2024 après 17 ans d\'attente ?',
                'bonne_reponse' => 'Al Horford',
                'mauvaise_1' => 'Kristaps Porziņģis',
                'mauvaise_2' => 'Robert Williams',
                'mauvaise_3' => 'Enes Kanter',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'basket',
                'question' => 'Quel tir signature à une main rendu célèbre par Kareem Abdul-Jabbar était réputé indéfendable ?',
                'bonne_reponse' => 'Le Skyhook',
                'mauvaise_1' => 'Le Fadeaway',
                'mauvaise_2' => 'Le Floater',
                'mauvaise_3' => 'Le Finger roll',
                'difficulte' => 'difficile',
            ],

            // ==========================================
            // TENNIS (slug: tennis)
            // ==========================================
            // --- Facile ---
            [
                'slug' => 'tennis',
                'question' => 'Sur quelle surface mythique se dispute le tournoi du Grand Chelem de Roland-Garros ?',
                'bonne_reponse' => 'Terre battue',
                'mauvaise_1' => 'Gazon',
                'mauvaise_2' => 'Dur (DecoTurf)',
                'mauvaise_3' => 'Moquette synthétique',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Combien de tournois majeurs composent le Grand Chelem de tennis chaque saison ?',
                'bonne_reponse' => '4',
                'mauvaise_1' => '3',
                'mauvaise_2' => '5',
                'mauvaise_3' => '6',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel champion espagnol a régné sur Roland-Garros avec un total record de 14 victoires ?',
                'bonne_reponse' => 'Rafael Nadal',
                'mauvaise_1' => 'Carlos Alcaraz',
                'mauvaise_2' => 'David Ferrer',
                'mauvaise_3' => 'Feliciano López',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Dans quelle ville britannique le prestigieux tournoi sur gazon de Wimbledon a-t-il lieu ?',
                'bonne_reponse' => 'Londres',
                'mauvaise_1' => 'Manchester',
                'mauvaise_2' => 'Édimbourg',
                'mauvaise_3' => 'Birmingham',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel maestro suisse réputé pour son revers à une main a remporté 20 titres du Grand Chelem ?',
                'bonne_reponse' => 'Roger Federer',
                'mauvaise_1' => 'Stan Wawrinka',
                'mauvaise_2' => 'Marc Rosset',
                'mauvaise_3' => 'Dominic Stricker',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel est le premier palier de points marqué par un joueur au cours d\'un jeu ordinaire ?',
                'bonne_reponse' => '15',
                'mauvaise_1' => '10',
                'mauvaise_2' => '5',
                'mauvaise_3' => '1',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur serbe détient le record masculin du plus grand nombre de titres du Grand Chelem ?',
                'bonne_reponse' => 'Novak Djokovic',
                'mauvaise_1' => 'Goran Ivanišević',
                'mauvaise_2' => 'Daniil Medvedev',
                'mauvaise_3' => 'Marat Safin',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Comment nomme-t-on un service gagnant sur lequel le receveur ne parvient même pas à toucher la balle ?',
                'bonne_reponse' => 'Un ace',
                'mauvaise_1' => 'Un smash',
                'mauvaise_2' => 'Un lob',
                'mauvaise_3' => 'Un passing-shot',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle joueuse américaine a dominé le tennis féminin moderne avec 23 titres du Grand Chelem en simple ?',
                'bonne_reponse' => 'Serena Williams',
                'mauvaise_1' => 'Venus Williams',
                'mauvaise_2' => 'Maria Sharapova',
                'mauvaise_3' => 'Lindsay Davenport',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Comment appelle-t-on le jeu décisif disputé lorsque les deux joueurs atteignent 6 jeux partout ?',
                'bonne_reponse' => 'Le tie-break',
                'mauvaise_1' => 'Le sudden death',
                'mauvaise_2' => 'Le money-time',
                'mauvaise_3' => 'Le set en or',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'De quelle couleur sont les balles de tennis homologuées en compétition officielle ?',
                'bonne_reponse' => 'Jaune',
                'mauvaise_1' => 'Blanche',
                'mauvaise_2' => 'Verte',
                'mauvaise_3' => 'Orange',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel jeune prodige espagnol a remporté l\'US Open, Wimbledon et Roland-Garros avant ses 22 ans ?',
                'bonne_reponse' => 'Carlos Alcaraz',
                'mauvaise_1' => 'Jannik Sinner',
                'mauvaise_2' => 'Casper Ruud',
                'mauvaise_3' => 'Holger Rune',
                'difficulte' => 'facile',
            ],

            // --- Moyen ---
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur est le dernier Français à avoir triomphé en simple messieurs à Roland-Garros (en 1983) ?',
                'bonne_reponse' => 'Yannick Noah',
                'mauvaise_1' => 'Henri Leconte',
                'mauvaise_2' => 'Guy Forget',
                'mauvaise_3' => 'Cédric Pioline',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel tournoi du Grand Chelem ouvre traditionnellement la saison chaque année au mois de janvier ?',
                'bonne_reponse' => 'Open d\'Australie',
                'mauvaise_1' => 'Roland-Garros',
                'mauvaise_2' => 'Wimbledon',
                'mauvaise_3' => 'US Open',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle joueuse française a remporté le tournoi de Wimbledon en 2013 ?',
                'bonne_reponse' => 'Marion Bartoli',
                'mauvaise_1' => 'Amélie Mauresmo',
                'mauvaise_2' => 'Mary Pierce',
                'mauvaise_3' => 'Caroline Garcia',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur italien est devenu numéro 1 mondial en 2024 après ses victoires en Australie et à l\'US Open ?',
                'bonne_reponse' => 'Jannik Sinner',
                'mauvaise_1' => 'Matteo Berrettini',
                'mauvaise_2' => 'Lorenzo Musetti',
                'mauvaise_3' => 'Fabio Fognini',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Combien de jeux d\'écart sont requis pour remporter un set ordinaire (ex: 6-4) ?',
                'bonne_reponse' => '2 jeux',
                'mauvaise_1' => '1 jeu',
                'mauvaise_2' => '3 jeux',
                'mauvaise_3' => '4 jeux',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Comment qualifie-t-on une balle frappée à la volée très près du filet qui retombe juste derrière ?',
                'bonne_reponse' => 'Un amorti',
                'mauvaise_1' => 'Un smash',
                'mauvaise_2' => 'Un lift',
                'mauvaise_3' => 'Un lob',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle compétition historique masculine par équipes nationales attribue le « Saladier d\'Argent » ?',
                'bonne_reponse' => 'La Coupe Davis',
                'mauvaise_1' => 'La Laver Cup',
                'mauvaise_2' => 'L\'ATP Cup',
                'mauvaise_3' => 'La Fed Cup',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle tradition vestimentaire stricte est imposée à tous les athlètes sur le gazon de Wimbledon ?',
                'bonne_reponse' => 'Tenue entièrement blanche',
                'mauvaise_1' => 'Short sombre exigé',
                'mauvaise_2' => 'Casquette obligatoire',
                'mauvaise_3' => 'Bandeau tricolore',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur écossais a décroché deux médailles d\'or olympiques en simple et deux titres à Wimbledon ?',
                'bonne_reponse' => 'Andy Murray',
                'mauvaise_1' => 'Tim Henman',
                'mauvaise_2' => 'Cameron Norrie',
                'mauvaise_3' => 'Greg Rusedski',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Dans quel complexe sportif new-yorkais se dispute annuellement l\'US Open ?',
                'bonne_reponse' => 'Flushing Meadows',
                'mauvaise_1' => 'Melbourne Park',
                'mauvaise_2' => 'Queen\'s Club',
                'mauvaise_3' => 'Key Biscayne',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle championne polonaise a accumulé les couronnes à Roland-Garros entre 2020 et 2024 ?',
                'bonne_reponse' => 'Iga Świątek',
                'mauvaise_1' => 'Aryna Sabalenka',
                'mauvaise_2' => 'Elena Rybakina',
                'mauvaise_3' => 'Agnieszka Radwańska',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle ancienne numéro 1 mondiale française a été directrice du tournoi de Roland-Garros ?',
                'bonne_reponse' => 'Amélie Mauresmo',
                'mauvaise_1' => 'Mary Pierce',
                'mauvaise_2' => 'Marion Bartoli',
                'mauvaise_3' => 'Nathalie Dechy',
                'difficulte' => 'moyen',
            ],

            // --- Difficile ---
            [
                'slug' => 'tennis',
                'question' => 'Quel Australien est le seul joueur de l\'histoire à avoir réalisé deux fois le Grand Chelem calendaire (1962 et 1969) ?',
                'bonne_reponse' => 'Rod Laver',
                'mauvaise_1' => 'Ken Rosewall',
                'mauvaise_2' => 'Roy Emerson',
                'mauvaise_3' => 'John Newcombe',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Combien de jeux a duré le match le plus long de l\'histoire du tennis entre Isner et Mahut à Wimbledon en 2010 ?',
                'bonne_reponse' => '183 jeux (70-68 au 5e)',
                'mauvaise_1' => '142 jeux',
                'mauvaise_2' => '164 jeux',
                'mauvaise_3' => '205 jeux',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle championne allemande a accompli le « Golden Slam » parfait en 1988 (4 Majeurs + Or Olympique) ?',
                'bonne_reponse' => 'Steffi Graf',
                'mauvaise_1' => 'Martina Navrátilová',
                'mauvaise_2' => 'Chris Evert',
                'mauvaise_3' => 'Monica Seles',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur suédois a remporté 5 fois d\'affilée Wimbledon et 6 Roland-Garros avant de se retirer à 26 ans ?',
                'bonne_reponse' => 'Björn Borg',
                'mauvaise_1' => 'Mats Wilander',
                'mauvaise_2' => 'Stefan Edberg',
                'mauvaise_3' => 'Robin Söderling',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur suédois a créé la sensation en devenant le premier à vaincre Rafael Nadal à Roland-Garros (en 2009) ?',
                'bonne_reponse' => 'Robin Söderling',
                'mauvaise_1' => 'Novak Djokovic',
                'mauvaise_2' => 'Roger Federer',
                'mauvaise_3' => 'Dominic Thiem',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quelle joueuse australienne détient le record historique absolu de titres du Grand Chelem en simple (24 sacres) ?',
                'bonne_reponse' => 'Margaret Court',
                'mauvaise_1' => 'Serena Williams',
                'mauvaise_2' => 'Billie Jean King',
                'mauvaise_3' => 'Evonne Goolagong',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'En quelle année la France de Yannick Noah a-t-elle remporté sa première Coupe Davis moderne face aux USA à Lyon ?',
                'bonne_reponse' => '1991',
                'mauvaise_1' => '1986',
                'mauvaise_2' => '1996',
                'mauvaise_3' => '2001',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel joueur américain a créé la surprise en remportant Roland-Garros à seulement 17 ans et 3 mois en 1989 ?',
                'bonne_reponse' => 'Michael Chang',
                'mauvaise_1' => 'Andre Agassi',
                'mauvaise_2' => 'Pete Sampras',
                'mauvaise_3' => 'Jim Courier',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'De quelle nationalité était Gustavo Kuerten, triple vainqueur de Roland-Garros (1997, 2000, 2001) ?',
                'bonne_reponse' => 'Brésilienne',
                'mauvaise_1' => 'Argentine',
                'mauvaise_2' => 'Chilienne',
                'mauvaise_3' => 'Espagnole',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel tournoi a accueilli la dernière finale de Grand Chelem jouée par Roger Federer en 2019 face à Djokovic ?',
                'bonne_reponse' => 'Wimbledon',
                'mauvaise_1' => 'Open d\'Australie',
                'mauvaise_2' => 'US Open',
                'mauvaise_3' => 'Roland-Garros',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel était le surnom de Pete Sampras, célèbre pour son service d\'une efficacité redoutable ?',
                'bonne_reponse' => 'Pistol Pete',
                'mauvaise_1' => 'The Rocket',
                'mauvaise_2' => 'The Bull',
                'mauvaise_3' => 'The Magician',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'tennis',
                'question' => 'Quel score minimum avec deux points d\'écart faut-il atteindre pour remporter un tie-break ordinaire ?',
                'bonne_reponse' => '7 points',
                'mauvaise_1' => '10 points',
                'mauvaise_2' => '5 points',
                'mauvaise_3' => '6 points',
                'difficulte' => 'difficile',
            ],

            // ==========================================
            // TOUS SPORTS (slug: multi)
            // ==========================================
            // --- Facile ---
            [
                'slug' => 'multi',
                'question' => 'Tous les combien d\'années les Jeux Olympiques d\'été ont-ils lieu en règle générale ?',
                'bonne_reponse' => '4 ans',
                'mauvaise_1' => '2 ans',
                'mauvaise_2' => '5 ans',
                'mauvaise_3' => '3 ans',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel sprinteur jamaïcain est l\'homme le plus rapide de l\'histoire avec son record du monde sur 100m (9s58) ?',
                'bonne_reponse' => 'Usain Bolt',
                'mauvaise_1' => 'Tyson Gay',
                'mauvaise_2' => 'Yohan Blake',
                'mauvaise_3' => 'Asafa Powell',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel judoka français poids lourd a décroché 3 médailles d\'or olympiques individuelles et plus de 10 titres mondiaux ?',
                'bonne_reponse' => 'Teddy Riner',
                'mauvaise_1' => 'David Douillet',
                'mauvaise_2' => 'Clarisse Agbegnenou',
                'mauvaise_3' => 'Djamel Bouras',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle couleur de maillot récompense le leader du classement général sur le Tour de France cycliste ?',
                'bonne_reponse' => 'Jaune',
                'mauvaise_1' => 'Vert',
                'mauvaise_2' => 'Blanc à pois rouges',
                'mauvaise_3' => 'Rose',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel nageur prodige français a conquis 4 médailles d\'or individuelles aux Jeux Olympiques de Paris 2024 ?',
                'bonne_reponse' => 'Léon Marchand',
                'mauvaise_1' => 'Florent Manaudou',
                'mauvaise_2' => 'Camille Lacourt',
                'mauvaise_3' => 'Alain Bernard',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Combien d\'anneaux entrelacés composent l\'emblème officiel des Jeux Olympiques ?',
                'bonne_reponse' => '5',
                'mauvaise_1' => '4',
                'mauvaise_2' => '6',
                'mauvaise_3' => '7',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Dans quel sport d\'hiver les joueurs poussent-ils un palet à l\'aide d\'une crosse sur la glace ?',
                'bonne_reponse' => 'Le hockey sur glace',
                'mauvaise_1' => 'Le curling',
                'mauvaise_2' => 'Le bobsleigh',
                'mauvaise_3' => 'Le patinage de vitesse',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle équipe nationale de rugby réalise la célèbre danse rituelle du « Haka » avant chaque rencontre ?',
                'bonne_reponse' => 'La Nouvelle-Zélande',
                'mauvaise_1' => 'L\'Australie',
                'mauvaise_2' => 'L\'Afrique du Sud',
                'mauvaise_3' => 'Les Fidji',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle est la distance exacte et officielle d\'une course de marathon en athlétisme ?',
                'bonne_reponse' => '42,195 km',
                'mauvaise_1' => '40 km',
                'mauvaise_2' => '45 km',
                'mauvaise_3' => '38,5 km',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle métropole a été la ville hôte des Jeux Olympiques et Paralympiques d\'été en 2024 ?',
                'bonne_reponse' => 'Paris',
                'mauvaise_1' => 'Tokyo',
                'mauvaise_2' => 'Los Angeles',
                'mauvaise_3' => 'Londres',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Sur quelle surface de combat traditionnelle s\'affrontent les judokas vêtus d\'un judogi ?',
                'bonne_reponse' => 'Un tatami',
                'mauvaise_1' => 'Un ring',
                'mauvaise_2' => 'Une piste',
                'mauvaise_3' => 'Un court',
                'difficulte' => 'facile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel pilote néerlandais a enchaîné les titres mondiaux de Formule 1 au volant de sa Red Bull ?',
                'bonne_reponse' => 'Max Verstappen',
                'mauvaise_1' => 'Lewis Hamilton',
                'mauvaise_2' => 'Charles Leclerc',
                'mauvaise_3' => 'Lando Norris',
                'difficulte' => 'facile',
            ],

            // --- Moyen ---
            [
                'slug' => 'multi',
                'question' => 'Quel nageur américain est l\'athlète le plus médaillé de l\'histoire des JO avec 23 médailles d\'or ?',
                'bonne_reponse' => 'Michael Phelps',
                'mauvaise_1' => 'Mark Spitz',
                'mauvaise_2' => 'Ryan Lochte',
                'mauvaise_3' => 'Caeleb Dressel',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Combien de points rapporte un essai non transformé au rugby à XV ?',
                'bonne_reponse' => '5 points',
                'mauvaise_1' => '3 points',
                'mauvaise_2' => '7 points',
                'mauvaise_3' => '4 points',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel perchiste suédois vole régulièrement au-dessus de 6,25 m et bat ses propres records du monde ?',
                'bonne_reponse' => 'Armand Duplantis',
                'mauvaise_1' => 'Renaud Lavillenie',
                'mauvaise_2' => 'Sergueï Bubka',
                'mauvaise_3' => 'Sam Kendricks',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle nation a remporté la Coupe du Monde de rugby à XV organisée en France en 2023 ?',
                'bonne_reponse' => 'Afrique du Sud',
                'mauvaise_1' => 'Nouvelle-Zélande',
                'mauvaise_2' => 'Angleterre',
                'mauvaise_3' => 'France',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel champion britannique détient conjointement avec Michael Schumacher le record de 7 titres mondiaux en F1 ?',
                'bonne_reponse' => 'Lewis Hamilton',
                'mauvaise_1' => 'Sebastian Vettel',
                'mauvaise_2' => 'Fernando Alonso',
                'mauvaise_3' => 'Alain Prost',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle est la durée d\'un round officiel dans un combat de boxe anglaise professionnelle masculine ?',
                'bonne_reponse' => '3 minutes',
                'mauvaise_1' => '2 minutes',
                'mauvaise_2' => '5 minutes',
                'mauvaise_3' => '4 minutes',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel coureur cycliste slovène a réussi le doublé Giro d\'Italie - Tour de France en 2024 ?',
                'bonne_reponse' => 'Tadej Pogačar',
                'mauvaise_1' => 'Primož Roglič',
                'mauvaise_2' => 'Jonas Vingegaard',
                'mauvaise_3' => 'Remco Evenepoel',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Combien de joueurs d\'une équipe de handball sont présents en même temps sur le terrain ?',
                'bonne_reponse' => '7',
                'mauvaise_1' => '6',
                'mauvaise_2' => '8',
                'mauvaise_3' => '5',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'En escrime, quelle arme s\'ajoute au fleuret et à l\'épée pour composer les trois disciplines olympiques ?',
                'bonne_reponse' => 'Le sabre',
                'mauvaise_1' => 'La dague',
                'mauvaise_2' => 'La rapière',
                'mauvaise_3' => 'Le javelot',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel sport d\'hiver combine la course en ski de fond et le tir à la carabine ?',
                'bonne_reponse' => 'Le biathlon',
                'mauvaise_1' => 'Le combiné nordique',
                'mauvaise_2' => 'Le bobsleigh',
                'mauvaise_3' => 'Le skeleton',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle nation dispute chaque hiver le Tournoi des Six Nations avec la France, l\'Angleterre, l\'Écosse, l\'Irlande et le Pays de Galles ?',
                'bonne_reponse' => 'L\'Italie',
                'mauvaise_1' => 'L\'Espagne',
                'mauvaise_2' => 'Le Portugal',
                'mauvaise_3' => 'La Géorgie',
                'difficulte' => 'moyen',
            ],
            [
                'slug' => 'multi',
                'question' => 'Dans quelle épreuve collective d\'athlétisme les relayeurs se passent-ils un témoin à pleine vitesse ?',
                'bonne_reponse' => 'Le relais 4x100m',
                'mauvaise_1' => 'Le 110m haies',
                'mauvaise_2' => 'Le 3000m steeple',
                'mauvaise_3' => 'Le décathlon',
                'difficulte' => 'moyen',
            ],

            // --- Difficile ---
            [
                'slug' => 'multi',
                'question' => 'Quel pilote français a remporté 4 titres de champion du monde de F1 et entretenu une rivalité mythique avec Senna ?',
                'bonne_reponse' => 'Alain Prost',
                'mauvaise_1' => 'Jean Alesi',
                'mauvaise_2' => 'René Arnoux',
                'mauvaise_3' => 'Didier Pironi',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel athlète tchèque a réussi l\'exploit inimaginable de remporter le 5 000m, le 10 000m et le marathon aux JO d\'Helsinki 1952 ?',
                'bonne_reponse' => 'Emil Zátopek',
                'mauvaise_1' => 'Paavo Nurmi',
                'mauvaise_2' => 'Abebe Bikila',
                'mauvaise_3' => 'Haile Gebrselassie',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'En quelle année la première édition du Tour de France cycliste s\'est-elle élancée ?',
                'bonne_reponse' => '1903',
                'mauvaise_1' => '1896',
                'mauvaise_2' => '1910',
                'mauvaise_3' => '1920',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Sous quel nom de naissance Mohamed Ali a-t-il été champion olympique de boxe à Rome en 1960 ?',
                'bonne_reponse' => 'Cassius Clay',
                'mauvaise_1' => 'Joe Frazier',
                'mauvaise_2' => 'Sonny Liston',
                'mauvaise_3' => 'George Foreman',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel est le score parfait maximal pouvant être réalisé dans une partie de bowling (12 strikes consécutifs) ?',
                'bonne_reponse' => '300 points',
                'mauvaise_1' => '200 points',
                'mauvaise_2' => '250 points',
                'mauvaise_3' => '400 points',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle gymnaste roumaine est entrée dans l\'histoire en obtenant la toute première note parfaite de 10.0 aux JO de Montréal 1976 ?',
                'bonne_reponse' => 'Nadia Comăneci',
                'mauvaise_1' => 'Simone Biles',
                'mauvaise_2' => 'Svetlana Khorkina',
                'mauvaise_3' => 'Larisa Latynina',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quel marathonien kényan a été le premier être humain à courir un marathon en moins de 2 heures lors d\'un défi à Vienne en 2019 ?',
                'bonne_reponse' => 'Eliud Kipchoge',
                'mauvaise_1' => 'Kelvin Kiptum',
                'mauvaise_2' => 'Kenenisa Bekele',
                'mauvaise_3' => 'Wilson Kipsang',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle judokate française ultra-dominante a été sextuple championne du monde en catégorie moins de 63 kg ?',
                'bonne_reponse' => 'Clarisse Agbegnenou',
                'mauvaise_1' => 'Lucie Décosse',
                'mauvaise_2' => 'Gévrise Émane',
                'mauvaise_3' => 'Céline Lebrun',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Sur quel circuit sarthois légendaire se déroule la course d\'endurance automobile des 24 Heures du Mans ?',
                'bonne_reponse' => 'Circuit des 24 Heures (Bugatti)',
                'mauvaise_1' => 'Circuit Paul Ricard',
                'mauvaise_2' => 'Magny-Cours',
                'mauvaise_3' => 'Spa-Francorchamps',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle distance de natation doit être parcourue lors d\'un triathlon olympique officiel (distance M) ?',
                'bonne_reponse' => '1 500 mètres',
                'mauvaise_1' => '1 000 mètres',
                'mauvaise_2' => '2 000 mètres',
                'mauvaise_3' => '3 800 mètres',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Dans quelle civilisation antique les Jeux Olympiques sont-ils nés en 776 avant J.-C. dans le Péloponnèse ?',
                'bonne_reponse' => 'Grèce antique',
                'mauvaise_1' => 'Rome antique',
                'mauvaise_2' => 'Égypte antique',
                'mauvaise_3' => 'Perse antique',
                'difficulte' => 'difficile',
            ],
            [
                'slug' => 'multi',
                'question' => 'Quelle légende ukrainienne du saut à la perche a battu 35 records du monde entre 1984 et 1994 ?',
                'bonne_reponse' => 'Sergueï Bubka',
                'mauvaise_1' => 'Renaud Lavillenie',
                'mauvaise_2' => 'Maksim Tarasov',
                'mauvaise_3' => 'Igor Trandenkov',
                'difficulte' => 'difficile',
            ],
        ];

        $total = 0;
        foreach ($questions as $q) {
            $catId = $categories[$q['slug']] ?? null;
            if (! $catId) continue;

            Question::create([
                'categorie_id' => $catId,
                'question' => $q['question'],
                'bonne_reponse' => $q['bonne_reponse'],
                'mauvaise_1' => $q['mauvaise_1'],
                'mauvaise_2' => $q['mauvaise_2'],
                'mauvaise_3' => $q['mauvaise_3'],
                'difficulte' => $q['difficulte'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
            $total++;
        }

        $this->command->info("QuestionSeeder : $total questions créées avec succès !");
    }
}
